gem update?

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,7 +19,7 @@ jobs:
       with:
         ruby-version: '2.7'
     - name: Enable bundler cache
-      uses: actions/cache@v4
+      uses: actions/cache@v3
       with:
         path: vendor/bundle
         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
@@ -27,9 +27,15 @@ jobs:
           ${{ runner.os }}-gems-
     - name: Install deps
       run: |
-        gem install bundler -v 2.4.22
+        gem uninstall bundler -a -x || true
+        gem install bundler -v 2.3.26
         bundle config path vendor/bundle
         bundle install --jobs 4 --retry 3
+#    - name: Install deps
+#      run: |
+#        gem install bundler -v 2.4.22
+#        bundle config path vendor/bundle
+#        bundle install --jobs 4 --retry 3
     - name: Setup deploy options
       id: setup
       run: |
